server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
spring:
  datasource:
    password: rie5amaeRa
    url: jdbc:mysql://db-5308.cs.dal.ca:3306/CSCI5308_14_DEVINT
    username: CSCI5308_14_DEVINT_USER
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mail:
  host: smtp.gmail.com
  port: 587
  username: foodbuddy.asdc5308@gmail.com
  password: password@asdc5308
  protocol: smtp
  tls: true
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com

